import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fitScript, mapToRoblox, type RbxInstance, type RbxValue, type RNode, type RobloxOptions } from "../src/roblox/map";
import { toLuau, toRbxmx } from "../src/roblox/output";

const card = JSON.parse(readFileSync(join(import.meta.dir, "fixtures", "roblox", "card.json"), "utf8")) as RNode;
const FIT: RobloxOptions = { mode: "fit", targetResolution: [1920, 1080], rasterize: "auto", scale: 2 };
const assets = () => ({ url: "rbxassetid://PENDING_1" });

const all = (i: RbxInstance): RbxInstance[] => [i, ...i.children.flatMap(all)];
const prop = (i: RbxInstance | undefined, k: string): RbxValue | undefined => i?.props.find(([p]) => p === k)?.[1];

describe("export_roblox fit mode", () => {
  const { root } = mapToRoblox(card, FIT, assets);
  const top = root.children[0]!;

  test("the root keeps Figma's pixel size and gets a UIScale driven by a LocalScript", () => {
    expect(prop(top, "Size")).toEqual({ t: "UDim2", xs: 0, xo: Math.round(card.w), ys: 0, yo: Math.round(card.h) });
    const scale = top.children.find((c) => c.className === "UIScale");
    const script = top.children.find((c) => c.className === "LocalScript");
    expect(prop(scale, "Name")).toEqual({ t: "string", v: "FitScale" });
    const source = prop(script, "Source") as { t: "Source"; v: string };
    expect(source.v).toContain('WaitForChild("FitScale")');
    expect(source.v).toContain("ViewportSize");
    expect(top.children.some((c) => c.className === "UIAspectRatioConstraint")).toBe(false);
  });

  test("no layer uses scale sizing, so proportions never drift between screens", () => {
    for (const i of all(top)) {
      for (const k of ["Size", "Position"]) {
        const v = prop(i, k) as { t: string; xs?: number; ys?: number } | undefined;
        if (v?.t !== "UDim2" || i === top) continue;
        // Only "fill" (scale 1) and constraint anchors (0.5 / 1) may use scale.
        for (const s of [v.xs!, v.ys!]) expect([0, 0.5, 1]).toContain(s);
      }
    }
  });

  test("the script is written into both outputs", () => {
    expect(toRbxmx(root)).toContain('<ProtectedString name="Source">-- Generated by Figma Bridge');
    const luau = toLuau(root);
    expect(luau).toContain('Instance.new("LocalScript")');
    expect(luau).toMatch(/\.Source = \[=*\[\n-- Generated by Figma Bridge/);
  });

  test("the scale fits the target screen and never overflows the viewport", () => {
    const src = fitScript(480, 706, 1920, 1080);
    // Same math as the Luau: min(viewport / target, viewport * 0.96 / size).
    const fit = (vx: number, vy: number) => Math.max(Math.min(vx / 1920, vy / 1080, (vx * 0.96) / 480, (vy * 0.96) / 706), 0.1);
    expect(fit(1920, 1080)).toBe(1);
    expect(fit(1280, 720)).toBeCloseTo(0.667, 2);
    expect(fit(800, 360)).toBeCloseTo(0.333, 2);
    expect(src).toContain("local TARGET = Vector2.new(1920, 1080)");
    expect(src).toContain("local SIZE = Vector2.new(480, 706)");
  });
});
